### ISSUE TITLE
TypeError: must start with number, buffer, array or string

### ISSUE THREAD

**Issue by victorb** [VictorBjelkholm/ipfsbin#12]
More errors:

```
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:139:11)
    at new Buffer (buffer.js:58:10)
    at /usr/src/app/bin/server.js:17:11
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:271:10)
```

**Comment by victorb** [comment]
Ain't gonna happen no mo! No more backend, no more bugs.
Hah
