### ISSUE TITLE
RangeNotSatisfiableError

### ISSUE THREAD

**Issue by victorb** [VictorBjelkholm/ipfsbin#6]
Express is outputting the following error:

```
RangeNotSatisfiableError: Range Not Satisfiable
    at SendStream.error (/usr/src/app/node_modules/express/node_modules/send/index.js:245:31)
    at SendStream.send (/usr/src/app/node_modules/express/node_modules/send/index.js:564:19)
    at /usr/src/app/node_modules/express/node_modules/send/index.js:669:12
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Need to do something like this:

```
http {
  proxy_buffer_size   128k;
  proxy_buffers   4 256k;
  proxy_busy_buffers_size   256k;
}
```

**Comment by victorb** [comment]
Not gonna happen anymore.

**Comment by FaizanZahid** [comment]
I have the exact same problem and it is happening on my Node JS server, see my site here [http://talkwithstranger.com/](http://talkwithstranger.com/) and my server crashes everytime due to this. How to fix it?

Here are my stackover flow question, if anyone can help ?
[http://stackoverflow.com/questions/37570346/node-js-app-crashing-itself-even-after-using-forever-js/37571484?noredirect=1#comment62633618_37571484](http://stackoverflow.com/questions/37570346/node-js-app-crashing-itself-even-after-using-forever-js/37571484?noredirect=1#comment62633618_37571484)

RangeNotSatisfiableError: Range Not Satisfiable
    at SendStream.error (/home/ubuntu/chat2/node_modules/express/node_modules/connect/node_modules/serve-static/node_modules/send/index.js:245:31)
    at SendStream.send (/home/ubuntu/chat2/node_modules/express/node_modules/connect/node_modules/serve-static/node_modules/send/index.js:564:19)
    at onstat (/home/ubuntu/chat2/node_modules/express/node_modules/connect/node_modules/serve-static/node_modules/send/index.js:624:10)
    at FSReqWrap.oncomplete (fs.js:82:15)
